# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(300, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(0, 0, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.input_num = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_num.setGeometry(QtCore.QRect(30, 60, 131, 21))
        self.input_num.setObjectName("input_num")
        self.comboBox_city = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_city.setGeometry(QtCore.QRect(170, 60, 101, 22))
        self.comboBox_city.setObjectName("comboBox_city")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.comboBox_city.addItem("")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(30, 90, 41, 23))
        self.add_button.setObjectName("add_button")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(170, 90, 101, 23))
        self.submit_button.setObjectName("submit_button")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(210, 150, 61, 23))
        self.exit_button.setObjectName("exit_button")
        self.reset_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(80, 90, 81, 23))
        self.reset_button.setObjectName("reset_button")
        self.empty_text_box = QtWidgets.QLabel(parent=self.centralwidget)
        self.empty_text_box.setGeometry(QtCore.QRect(30, 132, 131, 21))
        self.empty_text_box.setText("")
        self.empty_text_box.setObjectName("empty_text_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Nebraska Sale Tax Calculator"))
        self.comboBox_city.setItemText(0, _translate("MainWindow", "N/A"))
        self.comboBox_city.setItemText(1, _translate("MainWindow", "Omaha"))
        self.comboBox_city.setItemText(2, _translate("MainWindow", "Lincoln"))
        self.comboBox_city.setItemText(3, _translate("MainWindow", "Bellevue"))
        self.comboBox_city.setItemText(4, _translate("MainWindow", "Grand Island"))
        self.comboBox_city.setItemText(5, _translate("MainWindow", "Kearney"))
        self.comboBox_city.setItemText(6, _translate("MainWindow", "Fremont"))
        self.comboBox_city.setItemText(7, _translate("MainWindow", "Norfolk"))
        self.comboBox_city.setItemText(8, _translate("MainWindow", "Hastings"))
        self.comboBox_city.setItemText(9, _translate("MainWindow", "Columbus"))
        self.comboBox_city.setItemText(10, _translate("MainWindow", "Papillion"))
        self.add_button.setText(_translate("MainWindow", "add"))
        self.submit_button.setText(_translate("MainWindow", "submit"))
        self.exit_button.setText(_translate("MainWindow", "exit"))
        self.reset_button.setText(_translate("MainWindow", "reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

